// Date: 10/02/2013 20:46:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package firestarme.fires_cars.common;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelDerrik extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer leg3;
    ModelRenderer top;
    ModelRenderer leg4;
    ModelRenderer leg2;
    ModelRenderer drill;
    ModelRenderer mover;
    ModelRenderer leg1;
    ModelRenderer cross1;
    ModelRenderer cross2;
    ModelRenderer cross3;
    ModelRenderer cross4;
    ModelRenderer cross5;
    ModelRenderer cross6;
    ModelRenderer cross7;
    ModelRenderer cross8;
    ModelRenderer cross9;
    ModelRenderer cross10;
    ModelRenderer cross11;
    ModelRenderer cross12;
  
  public ModelDerrik()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 16, 2, 16);
      base.setRotationPoint(-8F, 0F, -8F);
      base.setTextureSize(128, 256);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 0);
      leg3.addBox(0F, 0F, 0F, 1, 32, 1);
      leg3.setRotationPoint(2F, -31F, -3F);
      leg3.setTextureSize(128, 256);
      leg3.mirror = true;
      setRotation(leg3, -0.1396263F, 0F, -0.1396263F);
      top = new ModelRenderer(this, 0, 0);
      top.addBox(0F, 0F, 0F, 8, 2, 8);
      top.setRotationPoint(-4F, -32F, -4F);
      top.setTextureSize(128, 256);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 0);
      leg4.addBox(0F, 0F, 0F, 1, 32, 1);
      leg4.setRotationPoint(2F, -31F, 2F);
      leg4.setTextureSize(128, 256);
      leg4.mirror = true;
      setRotation(leg4, 0.1396263F, 0F, -0.1396263F);
      cross4.mirror = false;
      leg2 = new ModelRenderer(this, 0, 0);
      leg2.addBox(0F, 0F, 0F, 1, 32, 1);
      leg2.setRotationPoint(-3F, -31F, 2F);
      leg2.setTextureSize(128, 256);
      leg2.mirror = true;
      setRotation(leg2, 0.1396263F, 0F, 0.1396263F);
      drill = new ModelRenderer(this, 0, 0);
      drill.addBox(0F, 0F, 0F, 2, 35, 2);
      drill.setRotationPoint(-1F, -34F, -1F);
      drill.setTextureSize(128, 256);
      drill.mirror = true;
      setRotation(drill, 0F, 0F, 0F);
      mover = new ModelRenderer(this, 0, 0);
      mover.addBox(0F, 0F, 0F, 4, 3, 4);
      mover.setRotationPoint(-2F, -4F, -2F);
      mover.setTextureSize(128, 256);
      mover.mirror = true;
      setRotation(mover, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 0);
      leg1.addBox(0F, 0F, 0F, 1, 32, 1);
      leg1.setRotationPoint(-3F, -31F, -3F);
      leg1.setTextureSize(128, 256);
      leg1.mirror = true;
      setRotation(leg1, -0.1396263F, 0F, 0.1396263F);
      cross1 = new ModelRenderer(this, 0, 0);
      cross1.addBox(0F, 0F, 0F, 12, 1, 1);
      cross1.setRotationPoint(-4.6F, -19F, -4.5F);
      cross1.setTextureSize(128, 256);
      cross1.mirror = true;
      setRotation(cross1, -0.1745329F, -0.1815142F, -0.9424778F);
      cross2 = new ModelRenderer(this, 0, 0);
      cross2.addBox(0F, 0F, 0F, 12, 1, 1);
      cross2.setRotationPoint(-4.5F, -19F, 4.5F);
      cross2.setTextureSize(128, 256);
      cross2.mirror = true;
      setRotation(cross2, -0.1745329F, 1.363102F, -0.9424778F);
      cross3 = new ModelRenderer(this, 0, 0);
      cross3.addBox(0F, 0F, 0F, 12, 1, 1);
      cross3.setRotationPoint(4.5F, -19F, 4.5F);
      cross3.setTextureSize(128, 256);
      cross3.mirror = true;
      setRotation(cross3, -0.1745329F, 2.984513F, -0.9424778F);
      cross4.mirror = true;
      cross4 = new ModelRenderer(this, 0, 0);
      cross4.addBox(0F, 0F, 0F, 12, 1, 1);
      cross4.setRotationPoint(4.5F, -19F, -4.5F);
      cross4.setTextureSize(128, 256);
      cross4.mirror = true;
      setRotation(cross4, -0.1745329F, -1.762782F, -0.9424778F);
      cross5 = new ModelRenderer(this, 0, 0);
      cross5.addBox(0F, 0F, 0F, 15, 1, 1);
      cross5.setRotationPoint(-7F, -2F, 7F);
      cross5.setTextureSize(128, 256);
      cross5.mirror = true;
      setRotation(cross5, -0.1745329F, 1.485275F, -0.6283185F);
      cross6 = new ModelRenderer(this, 0, 0);
      cross6.addBox(0F, 0F, 0F, 15, 1, 1);
      cross6.setRotationPoint(7F, -2F, 7F);
      cross6.setTextureSize(128, 256);
      cross6.mirror = true;
      setRotation(cross6, -0.1745329F, 3.056072F, -0.6283185F);
      cross7 = new ModelRenderer(this, 0, 0);
      cross7.addBox(0F, 0F, 0F, 15, 1, 1);
      cross7.setRotationPoint(7F, -2F, -7F);
      cross7.setTextureSize(128, 256);
      cross7.mirror = true;
      setRotation(cross7, -0.1745329F, -1.675516F, -0.6283185F);
      cross8 = new ModelRenderer(this, 0, 0);
      cross8.addBox(0F, 0F, 0F, 12, 1, 1);
      cross8.setRotationPoint(-3.6F, -19F, -4.5F);
      cross8.setTextureSize(128, 256);
      cross8.mirror = true;
      setRotation(cross8, -0.1745329F, 0.1500983F, 0.6806784F);
      cross9 = new ModelRenderer(this, 0, 0);
      cross9.addBox(0F, 0F, 0F, 13, 1, 1);
      cross9.setRotationPoint(-4.5F, -19F, 4F);
      cross9.setTextureSize(128, 256);
      cross9.mirror = true;
      setRotation(cross9, -0.1745329F, 1.729621F, 0.6981317F);
      cross10 = new ModelRenderer(this, 0, 0);
      cross10.addBox(0F, 0F, 0F, 12, 1, 1);
      cross10.setRotationPoint(4F, -19F, 4.5F);
      cross10.setTextureSize(128, 256);
      cross10.mirror = true;
      setRotation(cross10, -0.1745329F, -3.036873F, 0.6632251F);
      cross11 = new ModelRenderer(this, 0, 0);
      cross11.addBox(0F, 0F, 0F, 13, 1, 1);
      cross11.setRotationPoint(4.5F, -19F, -4F);
      cross11.setTextureSize(128, 256);
      cross11.mirror = true;
      setRotation(cross11, -0.1745329F, -1.48353F, 0.715585F);
      cross12 = new ModelRenderer(this, 0, 0);
      cross12.addBox(0F, 0F, 0F, 15, 1, 1);
      cross12.setRotationPoint(-7F, -2F, -7F);
      cross12.setTextureSize(128, 256);
      cross12.mirror = true;
      setRotation(cross12, -0.1745329F, -0.0942478F, -0.6283185F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    base.render(f5);
    leg3.render(f5);
    top.render(f5);
    leg4.render(f5);
    leg2.render(f5);
    drill.render(f5);
    mover.render(f5);
    leg1.render(f5);
    cross1.render(f5);
    cross2.render(f5);
    cross3.render(f5);
    cross4.render(f5);
    cross5.render(f5);
    cross6.render(f5);
    cross7.render(f5);
    cross8.render(f5);
    cross9.render(f5);
    cross10.render(f5);
    cross11.render(f5);
    cross12.render(f5);
  }
  
  public void renderModel(float f5){
	  base.render(f5);
	    leg3.render(f5);
	    top.render(f5);
	    leg4.render(f5);
	    leg2.render(f5);
	    drill.render(f5);
	    mover.render(f5);
	    leg1.render(f5);
	    cross1.render(f5);
	    cross2.render(f5);
	    cross3.render(f5);
	    cross4.render(f5);
	    cross5.render(f5);
	    cross6.render(f5);
	    cross7.render(f5);
	    cross8.render(f5);
	    cross9.render(f5);
	    cross10.render(f5);
	    cross11.render(f5);
	    cross12.render(f5);
	  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
