// Date: 30/01/2013 10:18:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package firestarme.fires_cars.common;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelCar extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Wheel1;
    ModelRenderer Wheel2;
    ModelRenderer Wheel3;
    ModelRenderer Windscreen;
    ModelRenderer Wheel4;
    ModelRenderer Back;
    ModelRenderer Right;
    ModelRenderer Left;
    ModelRenderer Radiator;
    ModelRenderer front;
  
  public ModelCar()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 10, 2, 12);
      Base.setRotationPoint(1.698641E-14F, 3F, -9.992007E-15F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Wheel1 = new ModelRenderer(this, 1, 14);
      Wheel1.addBox(0F, -1F, -2F, 1, 3, 3);
      Wheel1.setRotationPoint(10F, 4F, 10F);
      Wheel1.setTextureSize(64, 32);
      Wheel1.mirror = true;
      setRotation(Wheel1, 0F, 0F, 0F);
      Wheel2 = new ModelRenderer(this, 1, 14);
      Wheel2.addBox(0F, 0F, 0F, 1, 3, 3);
      Wheel2.setRotationPoint(10F, 3F, 1F);
      Wheel2.setTextureSize(64, 32);
      Wheel2.mirror = true;
      setRotation(Wheel2, 0F, 0F, 0F);
      Wheel3 = new ModelRenderer(this, 0, 14);
      Wheel3.addBox(0F, -1F, -2F, 1, 3, 3);
      Wheel3.setRotationPoint(-1F, 4F, 10F);
      Wheel3.setTextureSize(64, 32);
      Wheel3.mirror = true;
      setRotation(Wheel3, 0F, 0F, 0F);
      Windscreen = new ModelRenderer(this, 14, 18);
      Windscreen.addBox(0F, 0F, 0F, 8, 4, 1);
      Windscreen.setRotationPoint(1F, 1F, 1F);
      Windscreen.setTextureSize(64, 32);
      Windscreen.mirror = true;
      setRotation(Windscreen, 2.740167F, 0F, 0F);
      Wheel4 = new ModelRenderer(this, 0, 14);
      Wheel4.addBox(0F, 0F, 0F, 1, 3, 3);
      Wheel4.setRotationPoint(-1F, 3F, 1F);
      Wheel4.setTextureSize(64, 32);
      Wheel4.mirror = true;
      setRotation(Wheel4, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 14, 14);
      Back.addBox(0F, 0F, 0F, 10, 3, 1);
      Back.setRotationPoint(0F, 0F, 11F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Right = new ModelRenderer(this, 0, 14);
      Right.addBox(0F, 0F, 0F, 1, 3, 12);
      Right.setRotationPoint(9F, 0F, 0F);
      Right.setTextureSize(64, 32);
      Right.mirror = true;
      setRotation(Right, 0F, 0F, 0F);
      Left = new ModelRenderer(this, 0, 14);
      Left.addBox(0F, 0F, 0F, 1, 3, 12);
      Left.setRotationPoint(0F, 0F, 0F);
      Left.setTextureSize(64, 32);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      Radiator = new ModelRenderer(this, 38, 17);
      Radiator.addBox(0F, 0F, 0F, 4, 3, 3);
      Radiator.setRotationPoint(3F, 1F, -1F);
      Radiator.setTextureSize(64, 32);
      Radiator.mirror = true;
      setRotation(Radiator, 0F, 0F, 0F);
      front = new ModelRenderer(this, 26, 23);
      front.addBox(0F, 0F, 0F, 10, 3, 3);
      front.setRotationPoint(0F, 0F, 0F);
      front.setTextureSize(64, 32);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity,f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Wheel1.render(f5);
    Wheel2.render(f5);
    Wheel3.render(f5);
    Windscreen.render(f5);
    Wheel4.render(f5);
    Back.render(f5);
    Right.render(f5);
    Left.render(f5);
    Radiator.render(f5);
    front.render(f5);
  }
  
  public void renderModel(float f5){
	  Base.render(f5);
	    Wheel1.render(f5);
	    Wheel2.render(f5);
	    Wheel3.render(f5);
	    Windscreen.render(f5);
	    Wheel4.render(f5);
	    Back.render(f5);
	    Right.render(f5);
	    Left.render(f5);
	    Radiator.render(f5);
	    front.render(f5);  
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity,float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
